%% beamer/knitr slides 
%% for Statistical Modeling and Data Visualization course @ UMass
%% Nicholas Reich: nick [at] schoolph.umass.edu


\documentclass[table]{beamer}


\input{../../slide-includes/standard-knitr-beamer-preamble}

%        The following variables are assumed by the standard preamble:
%        Global variable containing module name:

\title{Hypothesis Testing and Regression}
%	Global variable containing module shortname:
%		(Currently unused, may be used in future.)
\newcommand{\ModuleShortname}{multRegression}
%	Global variable containing author name:
\author{Nicholas G Reich}
%	Global variable containing text of license terms:
\newcommand{\LicenseText}{Made available under the Creative Commons Attribution-ShareAlike 3.0 Unported License: http://creativecommons.org/licenses/by-sa/3.0/deed.en\textunderscore US }
%	Instructor: optional, can leave blank.
%		Recommended format: {Instructor: Jane Doe}
\newcommand{\Instructor}{}
%	Course: optional, can leave blank.
%		Recommended format: {Course: Biostatistics 101}
\newcommand{\Course}{}


\input{../../slide-includes/shortcuts}
\usepackage{bbm}

\hypersetup{colorlinks,linkcolor=,urlcolor=MainColor}


%	******	Document body begins here	**********************

\begin{document}

%	Title page
\begin{frame}[plain]
	\titlepage
\end{frame}

%	******	Everything through the above line must be placed at
%		the top of any TeX file using the statsTeachR standard
%		beamer preamble. 


<<ggplot2, echo=FALSE, message=FALSE>>=
library(ggplot2)
theme_set(theme_bw())
library(knitr)
opts_chunk$set(fig.align='center',fig.show='hold',size='footnotesize')
@

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% acutal slides
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}{Today's Lecture}

\begin{center}
{\em Extraordinary claims demand extraordinary evidence.}\\
-Carl Sagan, astronomer
\end{center}


\begin{block}{Today's central question}
How can we formally evaluate statistical evidence from a dataset in the context of regression?
\end{block}

\vspace{3em}

Based loosely on Kaplan, Chapters 13-15.

\end{frame}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}[fragile]{Example A: Is the stock market random?}

<<message=FALSE, warning=FALSE, eval=FALSE>>=
library(quantmod)
getSymbols("DJIA", src='FRED')
plot(DJIA)
@

<<fig.height=4.5, message=FALSE, warning=FALSE, echo=FALSE>>=
library(quantmod)
load("DJIA.rda")
plot(DJIA)
@

\end{frame} 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}[fragile]{Example A: Is the stock market random?}

\begin{block}{How could we measure whether this is a random walk?}
\end{block}

\end{frame} 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}[fragile]{Example A: Is the stock market random?}

One way to measure whether a string of \Sexpr{nrow(DJIA)} observations are random is to measure how far from the starting value the final value is. In our real data, we can calculate this as:

<<>>=
djia <- as.data.frame(DJIA)
djia[nrow(djia),] - djia[1,]
@

\end{frame} 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}[fragile]{Example A: Is the stock market random?}

Let's assume that there is a hypothetical world where the stock market does fluctuate randomly up or down based on the percentages we observed in the real data. We could calculate this as

<<message=FALSE>>=
library(dplyr)
djia <- mutate(djia, pct.change = (lag(DJIA)-DJIA)/DJIA)
summary(djia)
@

\end{frame} 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}[fragile]{Example A: Is the stock market random?}

Now, for a small simulation:

<<message=FALSE>>=

@

\end{frame} 


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{frame}{Circle of Life}

\begin{figure}[t]
    \includegraphics[width=.8\textwidth]{../../slide-includes/CircleOfLife.pdf}  
\end{figure}

\end{frame} 



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\begin{frame}[fragile]{Today's key topics}

\bi
    \myitem Sampling distributions
    \myitem Standard error
    \myitem Confidence errors and intervals for coefficients
    \myitem Prediction intervals for future observations
\ei

\end{frame}



\end{document}
